blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/hc0830/opensearch-face-recognition/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/hc0830/opensearch-face-recognition/wiki
    about: Check our documentation and guides
  - name: 🔒 Security Issues
    url: https://github.com/hc0830/opensearch-face-recognition/security/advisories/new
    about: Report security vulnerabilities privately
